import styled from 'styled-components'

export const Container = styled.div`
  display: grid;
  place-items: center;
  width: 100vw;
  height: 100vh;
  background: ${(props) => props.theme['base-background']};

  /***************************************************
 * Generated by SVG Artista on 12/22/2022, 1:38:01 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

  @-webkit-keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 153.08726501464844px;
      stroke-dasharray: 153.08726501464844px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 153.08726501464844px;
    }
  }

  @keyframes animate-svg-stroke-1 {
    0% {
      stroke-dashoffset: 153.08726501464844px;
      stroke-dasharray: 153.08726501464844px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 153.08726501464844px;
    }
  }

  .svg-elem-1 {
    -webkit-animation: animate-svg-stroke-1 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0s both,
      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
    animation: animate-svg-stroke-1 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0s
        both,
      animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
  }

  @-webkit-keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 846.809814453125px;
      stroke-dasharray: 846.809814453125px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 846.809814453125px;
    }
  }

  @keyframes animate-svg-stroke-2 {
    0% {
      stroke-dashoffset: 846.809814453125px;
      stroke-dasharray: 846.809814453125px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 846.809814453125px;
    }
  }

  @-webkit-keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(50, 148, 248);
    }
  }

  @keyframes animate-svg-fill-2 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(50, 148, 248);
    }
  }

  .svg-elem-2 {
    -webkit-animation: animate-svg-stroke-2 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s both,
      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
    animation: animate-svg-stroke-2 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.12s
        both,
      animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
  }

  @-webkit-keyframes animate-svg-stroke-3 {
    0% {
      stroke-dashoffset: 172px;
      stroke-dasharray: 172px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 172px;
    }
  }

  @keyframes animate-svg-stroke-3 {
    0% {
      stroke-dashoffset: 172px;
      stroke-dasharray: 172px;
    }

    100% {
      stroke-dashoffset: 0;
      stroke-dasharray: 172px;
    }
  }

  @-webkit-keyframes animate-svg-fill-3 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(255, 255, 255);
    }
  }

  @keyframes animate-svg-fill-3 {
    0% {
      fill: transparent;
    }

    100% {
      fill: rgb(255, 255, 255);
    }
  }

  .svg-elem-3 {
    -webkit-animation: animate-svg-stroke-3 1s
        cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s both,
      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
    animation: animate-svg-stroke-3 1s cubic-bezier(0.47, 0, 0.745, 0.715) 0.24s
        both,
      animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
  }
`
